global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    service: transaction-service

scrape_configs:
  - job_name: transaction-service
    static_configs:
      - targets: ["app:8080"]
    metrics_path: /metrics

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
